/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as SessionRouteImport } from './routes/session'
import { Route as AppControllersRouteImport } from './routes/_app/controllers'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppFindRouteImport } from './routes/_app/find'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as PreparingGameIdRouteImport } from './routes/preparing.$gameId'
import { Route as AppControllersControllerIdRouteImport } from './routes/_app/controllers.$controllerId'
import { Route as AppFindGameIdRouteImport } from './routes/_app/find.$gameId'
import { Route as AppGameGameIdRouteImport } from './routes/_app/game.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AppControllersRoute = AppControllersRouteImport.update({
  id: '/controllers',
  path: '/controllers',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppFindRoute = AppFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const PreparingGameIdRoute = PreparingGameIdRouteImport.update({
  id: '/preparing/$gameId',
  path: '/preparing/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppControllersControllerIdRoute =
  AppControllersControllerIdRouteImport.update({
    id: '/$controllerId',
    path: '/$controllerId',
    getParentRoute: () => AppControllersRoute,
  } as any)
const AppFindGameIdRoute = AppFindGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => AppFindRoute,
} as any)
const AppGameGameIdRoute = AppGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/session': typeof SessionRoute
  '/controllers': typeof AppControllersRouteWithChildren
  '/devices': typeof AppDevicesRoute
  '/find': typeof AppFindRouteWithChildren
  '/home': typeof AppHomeRoute
  '/library': typeof AppLibraryRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/preparing/$gameId': typeof PreparingGameIdRoute
  '/controllers/$controllerId': typeof AppControllersControllerIdRoute
  '/find/$gameId': typeof AppFindGameIdRoute
  '/game/$gameId': typeof AppGameGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/session': typeof SessionRoute
  '/controllers': typeof AppControllersRouteWithChildren
  '/devices': typeof AppDevicesRoute
  '/find': typeof AppFindRouteWithChildren
  '/home': typeof AppHomeRoute
  '/library': typeof AppLibraryRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/preparing/$gameId': typeof PreparingGameIdRoute
  '/controllers/$controllerId': typeof AppControllersControllerIdRoute
  '/find/$gameId': typeof AppFindGameIdRoute
  '/game/$gameId': typeof AppGameGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/connect': typeof ConnectRoute
  '/session': typeof SessionRoute
  '/_app/controllers': typeof AppControllersRouteWithChildren
  '/_app/devices': typeof AppDevicesRoute
  '/_app/find': typeof AppFindRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/preparing/$gameId': typeof PreparingGameIdRoute
  '/_app/controllers/$controllerId': typeof AppControllersControllerIdRoute
  '/_app/find/$gameId': typeof AppFindGameIdRoute
  '/_app/game/$gameId': typeof AppGameGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/session'
    | '/controllers'
    | '/devices'
    | '/find'
    | '/home'
    | '/library'
    | '/profile'
    | '/search'
    | '/settings'
    | '/preparing/$gameId'
    | '/controllers/$controllerId'
    | '/find/$gameId'
    | '/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/session'
    | '/controllers'
    | '/devices'
    | '/find'
    | '/home'
    | '/library'
    | '/profile'
    | '/search'
    | '/settings'
    | '/preparing/$gameId'
    | '/controllers/$controllerId'
    | '/find/$gameId'
    | '/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/connect'
    | '/session'
    | '/_app/controllers'
    | '/_app/devices'
    | '/_app/find'
    | '/_app/home'
    | '/_app/library'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/settings'
    | '/preparing/$gameId'
    | '/_app/controllers/$controllerId'
    | '/_app/find/$gameId'
    | '/_app/game/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  SessionRoute: typeof SessionRoute
  PreparingGameIdRoute: typeof PreparingGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/controllers': {
      id: '/_app/controllers'
      path: '/controllers'
      fullPath: '/controllers'
      preLoaderRoute: typeof AppControllersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/find': {
      id: '/_app/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AppFindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/preparing/$gameId': {
      id: '/preparing/$gameId'
      path: '/preparing/$gameId'
      fullPath: '/preparing/$gameId'
      preLoaderRoute: typeof PreparingGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/controllers/$controllerId': {
      id: '/_app/controllers/$controllerId'
      path: '/$controllerId'
      fullPath: '/controllers/$controllerId'
      preLoaderRoute: typeof AppControllersControllerIdRouteImport
      parentRoute: typeof AppControllersRoute
    }
    '/_app/find/$gameId': {
      id: '/_app/find/$gameId'
      path: '/$gameId'
      fullPath: '/find/$gameId'
      preLoaderRoute: typeof AppFindGameIdRouteImport
      parentRoute: typeof AppFindRoute
    }
    '/_app/game/$gameId': {
      id: '/_app/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof AppGameGameIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppControllersRouteChildren {
  AppControllersControllerIdRoute: typeof AppControllersControllerIdRoute
}

const AppControllersRouteChildren: AppControllersRouteChildren = {
  AppControllersControllerIdRoute: AppControllersControllerIdRoute,
}

const AppControllersRouteWithChildren = AppControllersRoute._addFileChildren(
  AppControllersRouteChildren,
)

interface AppFindRouteChildren {
  AppFindGameIdRoute: typeof AppFindGameIdRoute
}

const AppFindRouteChildren: AppFindRouteChildren = {
  AppFindGameIdRoute: AppFindGameIdRoute,
}

const AppFindRouteWithChildren =
  AppFindRoute._addFileChildren(AppFindRouteChildren)

interface AppRouteChildren {
  AppControllersRoute: typeof AppControllersRouteWithChildren
  AppDevicesRoute: typeof AppDevicesRoute
  AppFindRoute: typeof AppFindRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppGameGameIdRoute: typeof AppGameGameIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppControllersRoute: AppControllersRouteWithChildren,
  AppDevicesRoute: AppDevicesRoute,
  AppFindRoute: AppFindRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppGameGameIdRoute: AppGameGameIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConnectRoute: ConnectRoute,
  SessionRoute: SessionRoute,
  PreparingGameIdRoute: PreparingGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
